### ISSUE TITLE
Checkout unable to give Camera permission to Tamara

### ISSUE THREAD

**Issue by AsimNGI** [Shopify/checkout-sheet-kit-android#113]
### What area is the issue related to?

Checkout Sheet Kit

### What version of the package are you using?

2.0.1

### Steps to Reproduce

1. Open Checkout
2. Go with any installment plan, in my case it's Tamara.
3. Tamara asks for ID Verification where the camera opens
4. Checkout unable to give Camera Permissions to Tamara

### Expected Behavior

Camera should open as Camera permission is already given and don't ask for camera permission again and again.

### Actual Behavior

Unable to give Camera permission to Tamara & asking for permissions again & again. However Camera permission is already given

### Screenshots/Videos/Log output

![Asking for permission](https://github.com/user-attachments/assets/23bebcd5-8ca4-4d99-a8dc-bdbb8026900c)

### Storefront domain

https://revibe.me/

**Comment by kiftio** [comment]
A new version has been released which exposes an onPermissionRequest() callback in the event processor.

You should now be able to implement that to grant access to the camera (and/or microphone) in the checkout WebView.

There's a basic implementation in the MobileBuyIntegration sample app
