### ISSUE TITLE
Checkout page requires auth

### ISSUE THREAD

**Issue by nAkhmedov** [Shopify/checkout-sheet-kit-android#121]
### What area is the issue related to?

Checkout Sheet Kit

### What version of the package are you using?

3.0.4

### Reproducible sample code

We are using this library to open shopify checkout page, buyer identity is attached to the cart. However checkout page is requiring authorization. How to open checkout page without auth?

### Steps to Reproduce

* Add product to cart
* Open checkout url

### Expected Behavior

The checkout page should not require auth. Because, buyer identity is attached to cart.

### Actual Behavior

The checkout page is requiring auth

### Storefront domain

https://a9dc00-93.myshopify.com

**Comment by markmur** [comment]
Hey @nAkhmedov, how are you authenticating the user? Are you attaching a `customerAccessToken` in the `buyerIdentity` object of the CartInput?

https://shopify.dev/docs/api/storefront/2024-04/input-objects/CartBuyerIdentityInput

**Comment by kiftio** [comment]
Unfortunately, attaching a `customerAccessToken` to the cart doesn't **currently** fully authenticate the customer. There's an ongoing project that is looking to change that, with a couple of security related limitations.

Until then, if you're a plus merchant, you could look into using [multipass](https://github.com/Shopify/checkout-sheet-kit-android?tab=readme-ov-file#multipass) to fully authenticate customers, but it might be worth holding on for the above change.

**Comment by nAkhmedov** [comment]
> Hey [@nAkhmedov](https://github.com/nAkhmedov), how are you authenticating the user? Are you attaching a `customerAccessToken` in the `buyerIdentity` object of the CartInput?
> 
> https://shopify.dev/docs/api/storefront/2024-04/input-objects/CartBuyerIdentityInput

yes

**Comment by nAkhmedov** [comment]
> Unfortunately, attaching a `customerAccessToken` to the cart doesn't **currently** fully authenticate the customer. There's an ongoing project that is looking to change that, with a couple of security related limitations.
> 
> Until then, if you're a plus merchant, you could look into using [multipass](https://github.com/Shopify/checkout-sheet-kit-android?tab=readme-ov-file#multipass) to fully authenticate customers, but it might be worth holding on for the above change.

looking for the solution asap

**Comment by kiftio** [comment]
Issue is not stale, work on the related project is continuing

**Comment by kiftio** [comment]
Hi @naveenjangra2 you should be able to do something similar (attaching the customerAccessToken to the cart buyerIdentity) with legacy customer accounts.

**Comment by naveenjangra2** [comment]
Hi @kiftio 

val checkoutLit: MutableList<Storefront.CartLineInput> = mutableListOf()
        list.forEach {
            checkoutLit
                .add(Storefront.CartLineInput(ID(it.varientID))
                    .setQuantity(it.totalQuantity))
        }

        val buyerIdentityInput = Storefront
            .CartBuyerIdentityInput()
            .setCustomerAccessToken(accessToken)

        return mutation { mutationQuery: MutationQuery ->
            mutationQuery
                .cartCreate(
                    {
                        it.input(
                            Storefront.CartInput()
                                .setBuyerIdentity(buyerIdentityInput)
                                .setLinesInput(Input.value(checkoutLit))
                        )
                    },
                    {
                        it.userErrors {
                            it
                                .field()
                                .message()
                                .code()
                        }
                        it.cart {
                            it
                                .checkoutUrl()
                        }
                    }
                )
        }

This is the thing we are doing. But it is not working.
implementation "com.shopify:checkout-sheet-kit:3.3.0"
implementation "com.shopify.mobilebuysdk:buy3:2025.4.0"

**Comment by naveenjangra2** [comment]
x-request-id af1221df-2803-4e11-8b11-8e7f1d1655fb-1746800241

shopid 60081799210

**Comment by kiftio** [comment]
Looking through the logs I can see an issue where the IP address changes between cart creation (IPv6) and opening the checkout URL (IPv4). The IP mismatch is preventing authentication. To stop that from happening you'll need to configure your domain for IPv6.

There's a help page here: https://help.shopify.com/en/manual/domains/ipv6_support

**Comment by naveenjangra2** [comment]
How can we fix it? Cart creation is done via the mobile buy SDK. and the URL is opened from the checkout sheet.

in IOS it is working.

**Comment by naveenjangra2** [comment]
We need to force the mobile buy SDK to use ipv4

**Comment by kiftio** [comment]
Can you expand a little? I still see IP mismatch logs for what look like the most recent requests

**Comment by naveenjangra2** [comment]
@kiftio
it is working fine in iOS on the same network. In android when we get the cart data we got the buyer identity as well. but it is not authenticated the user.

**Comment by kiftio** [comment]
This authentication isn't part of Checkout Sheet Kit, there's no code in this repo that enables it, it's part of the Storefront / Cart API.  

The difference may be in how each platform supports IPv6. If you follow the guide and it still isn't working, let me know.
