### ISSUE TITLE
Modal status bar margin is incorrect on some devices

### ISSUE THREAD

**Issue by DenisBronx** [Shopify/checkout-sheet-kit-android#71]
I'm on the **SDK version 1.0.0** and I notice a UI bug on some devices.
On my Pixel 4a (android version 13) the modal looks fine.

<img src="https://github.com/Shopify/checkout-sheet-kit-android/assets/10074238/4fd8b205-8cc3-43d4-804d-f3e2004019e6" width="30%">

But on my Emulator (Pixel 2 version 13) the modal has some extra grey space at the bottom and is hiding half of the status bar.

<img src="https://github.com/Shopify/checkout-sheet-kit-android/assets/10074238/c8b786d4-97da-460e-883c-b1c6223fee72" width="30%">

I tried switching from gesture navigation to 3-buttons navigation but the issue persists.

**Comment by kiftio** [comment]
Hi @DenisBronx Sorry for the slow reply. Are you still seeing this? 

When testing on the emulator with pixel 2, Android version 13, this is what I see:

<img width="758" alt="Screenshot 2024-05-16 at 15 31 54" src="https://github.com/Shopify/checkout-sheet-kit-android/assets/15106863/dd8c94af-d67e-46cc-bed3-8c5ecd63f0b5">

**Comment by DenisBronx** [comment]
hi @kiftio, I still the issue but it seems to affect only emulators.
It works fine with all the physical devices we tested
