### ISSUE TITLE
White screen on checkout and crash

### ISSUE THREAD

**Issue by cka29** [Shopify/checkout-sheet-kit-android#77]
When I have an active cart and update the carts line items by using the according mutation, I use the checkout sheets preload feature. Opening the sheet after updating the cart line items results in a white screen and this log message
```
E/chromium(29079): [ERROR:aw_browser_terminator.cc(154)] Renderer process (29602) crash detected (code -1).
W/cr_AwContents(29079): Application attempted to call on a destroyed WebView
W/cr_AwContents(29079): java.lang.Throwable
W/cr_AwContents(29079): 	at org.chromium.android_webview.AwContents.s(chromium-TrichromeWebViewGoogle6432.aab-stable-616717833:10)
W/cr_AwContents(29079): 	at com.android.webview.chromium.WebViewChromium.addJavascriptInterface(chromium-TrichromeWebViewGoogle6432.aab-stable-616717833:34)
W/cr_AwContents(29079): 	at android.webkit.WebView.addJavascriptInterface(WebView.java:1928)
W/cr_AwContents(29079): 	at com.shopify.checkoutsheetkit.CheckoutWebView.onAttachedToWindow(CheckoutWebView.kt:117)
W/cr_AwContents(29079): 	at android.view.View.dispatchAttachedToWindow(View.java:21291)
W/cr_AwContents(29079): 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3491)
6
W/cr_AwContents(29079): 	at android.view.ViewGroup.dispatchAttachedToWindow(ViewGroup.java:3498)
W/cr_AwContents(29079): 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2771)
W/cr_AwContents(29079): 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2286)
W/cr_AwContents(29079): 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:8948)
W/cr_AwContents(29079): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1231)
W/cr_AwContents(29079): 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1239)
W/cr_AwContents(29079): 	at android.view.Choreographer.doCallbacks(Choreographer.java:899)
W/cr_AwContents(29079): 	at android.view.Choreographer.doFrame(Choreographer.java:832)
W/cr_AwContents(29079): 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1214)
W/cr_AwContents(29079): 	at android.os.Handler.handleCallback(Handler.java:942)
W/cr_AwContents(29079): 	at android.os.Handler.dispatchMessage(Handler.java:99)
W/cr_AwContents(29079): 	at android.os.Looper.loopOnce(Looper.java:201)
W/cr_AwContents(29079): 	at android.os.Looper.loop(Looper.java:288)
W/cr_AwContents(29079): 	at android.app.ActivityThread.main(ActivityThread.java:7898)
W/cr_AwContents(29079): 	at java.lang.reflect.Method.invoke(Native Method)
W/cr_AwContents(29079): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
W/cr_AwContents(29079): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
W/Parcel  (29079): Expecting binder but got null!****
```
When I open the sheet again it works.

**Comment by kiftio** [comment]
I believe we use the same pattern in the MobileBuyIntegration sample app (`cartCreate`, then `cartLinesAdd` plus preloading), but I haven't seen this issue there.

Does preloading always results in a white screen? Or is it intermittent?

Could you let me know the version of the library you're using, the shop domain could also be useful for checking logs.  Any details about the the device / Android version would be great too.

Thanks

**Comment by cka29** [comment]
> I believe we use the same pattern in the MobileBuyIntegration sample app (`cartCreate`, then `cartLinesAdd` plus preloading), but I haven't seen this issue there.
> 
> Does preloading always results in a white screen? Or is it intermittent?
> 
> Could you let me know the version of the library you're using, the shop domain could also be useful for checking logs. Any details about the the device / Android version would be great too.
> 
> Thanks

I've built the example app from this repo and there it works just fine! The preloading "works" but when presenting the checkout sheet afterwards it fails. But only the first time presenting the sheet after a preload. The second time always works.

Issue happens on android 13 pixel 4, using v1.0.0 of checkout sheet android. Maybe one more hint (which could be the issue here and is not in your responsibility) I'm using flutter for the app and to call the android implementation for the sheet. Will look more into the implementation for our cross-platform usecase. I think we can close this issue for now. Thank you for your hint about the example app!
