### ISSUE TITLE
Google Pay express checkout option doesn't appear

### ISSUE THREAD

**Issue by matteoSANE** [Shopify/checkout-sheet-kit-android#92]
### What area is the issue related to?

Checkout Sheet Kit

### What version of the package are you using?

2.0.1

### Do you have a minimum reproducible example?

I want to present a native checkout dialog in my Android application with this line of code

`ShopifyCheckoutSheetKit.present(checkoutUrl, context, checkoutEventProcessor)`

The dialog opens properly but the google pay button doesn’t appear even though it’s one of the payments option and I'm able to see it in the web checkout page loaded on the browser.

### Steps to Reproduce

Get a valid checkout url.
Open a native checkout dialog using the present function.

### Expected Behavior

I want to see the Google Pay express checkout button on top of the native checkout dialog and place the order using this payment option.

### Actual Behavior

The native checkout dialog opens correctly but the google pay button doesn’t appear

### Screenshots/Videos/Log output

![Screenshot_20240503_084104](https://github.com/Shopify/checkout-sheet-kit-android/assets/3897277/5f4e3349-aa1d-40f1-9a05-11240a46e0f8)

**Comment by dmengelt** [comment]
We are looking into this. I promise 😉 Unfortunately I can't give you a timeline at the moment.

**Comment by DenisBronx** [comment]
Could we please reopen this one?

**Comment by dmengelt** [comment]
FYI we are working on it!

**Comment by DenisBronx** [comment]
Can we please reopen this?

**Comment by matteoSANE** [comment]
Any news on the resolution of this issue?

**Comment by JohnUgwuadi** [comment]
Yeah, any news? This would be a great feature

**Comment by dmengelt** [comment]
We are making progress 😉

As a first step, see [here](https://issues.chromium.org/issues/381849264) for Payment Request API availability in WebViews. This change is a requirement for Google Pay to work within WebViews.

**Comment by dmengelt** [comment]
Ah yes the PR #201 got merged and since version 3.4.0 Google Pay works. See the release notes [here](https://github.com/Shopify/checkout-sheet-kit-android/releases/tag/3.4.0). 

@kiftio I guess this issue can be closed.
